apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterlab
  template:
    metadata:
      labels:
        app: jupyterlab
    spec:
      containers:
      - name: jupyterlab
        image: elijun831/qiskit-on-docker:jupyterlab
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: jupyterlab-data
          mountPath: /app/notebooks
        - name: jupyterlab-config
          mountPath: /home/appuser/.jupyter/jupyter_lab_config.py
          subPath: jupyter_lab_config.py
      volumes:
      - name: jupyterlab-data
        persistentVolumeClaim:
          claimName: jupyterlab-pvc
      - name: jupyterlab-config
        configMap:
          name: jupyterlab-config
