apiVersion: apps/v1
kind: Deployment
metadata:
  name: qiskit-on-docker-jupyterlab-deployment
spec:
  replicas: 3 # Can be any number
  selector:
    matchLabels:
      app: qiskit-on-docker-jupyterlab
  template:
    metadata:
      labels:
        app: qiskit-on-docker-jupyterlab
    spec:
      containers:
      - name: qiskit-on-docker-jupyterlab
        image: elijun831/qiskit-on-docker:jupyterlab
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: qiskit-on-docker-jupyterlab-storage
          mountPath: /app/notebooks
        - name: tls-secret
          mountPath: /etc/ssl
          readOnly: true
        env:
        - name: SSL_CERTFILE
          value: /etc/ssl/localhost.pem
        - name: SSL_KEYFILE
          value: /etc/ssl/localhost.key
      volumes:
      - name: qiskit-on-docker-jupyterlab-storage
        persistentVolumeClaim:
          claimName: qiskit-on-docker-jupyterlab-pvc
      - name: tls-secret
        secret:
          secretName: jupyterlab-tls
