apiVersion: v1
kind: Service
metadata:
  name: qiskit-on-docker-jupyterlab-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8888
  selector:
    app: qiskit-on-docker-jupyterlab
