version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: elijun831/qiskit-on-docker:1.0.0
    networks:
      - mynetwork
    volumes:
      - /notebooks:/app/notebooks  # Adjust the host path as needed
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    command: ["poetry", "run", "python", "app.py"]

  jupyterlab:
    image: elijun831/qiskit-on-docker:1.0.0  # Use the same image as the 'web' service
    ports:
      - "8888:8888"
    networks:
      - mynetwork
    volumes:
      - ./notebooks:/app/notebooks  # Adjust the host path as needed
      - /notebooks
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    command: ["poetry", "run", "jupyter", "lab", "--ip=0.0.0.0", "--no-browser", "--allow-root", "--port=8888", "--NotebookApp.port_retries=0", "--NotebookApp.allow_origin='*'"]

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
      - "8443:443"
      - "443:443"
      - "80:80"
    networks:
      - mynetwork
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  
      - ./certs:/etc/nginx/certs  
    depends_on:
      - jupyterlab  # Ensure that Nginx starts after JupyterLab
    command: ["/bin/sh", "-c", "exec nginx -g 'daemon off;'"]

networks:
  mynetwork:
    driver: bridge
