services:
  web:
    build:
      context: .
      target: runtime
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    image: elijun831/qiskit-on-docker:1.0.0
    networks:
      - mynetwork
    volumes:
      - /notebooks:/app/notebooks  # Adjust the host path as needed

  jupyterlab:
    build:
      context: .
      target: runtime
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    networks:
      - mynetwork
    ports:
      - "8888:8888"
      - "5678:5678"
      - "8443:443"
    volumes:
      - ./notebooks:/app/notebooks  # Adjust the host path as needed

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynetwork
    depends_on:
      - web
    links:
      - web

networks:
  mynetwork:
    driver: bridge
