services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - mynetwork

  qiskitondocker:
    build:
      context: .
      dockerfile: Dockerfile
    image: elijun831/qiskit-on-docker:1.0.0
    container_name: qiskitondocker
    ports:
      - "8888:8888"
      - "5678:5678"
    volumes:
      - ./notebooks:/notebooks
    networks:
      - mynetwork
    environment:
      - SSL_CERT=/etc/nginx/certs/_wildcard.qiskitondocker.dev+3.pem
      - SSL_CERT_KEY=/etc/nginx/certs/_wildcard.qiskitondocker.dev+3-key.pem
      - DH_PARAM=/etc/nginx/certs/dhparam.pem
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_PASSWORD=password
    restart: always
    hostname: qiskitondocker

networks:
  mynetwork:
    driver: bridge
