[tool.poetry]
name = "qiskit-packages"
version = "1.0.0"
description = "Qiskit and quantum computing-related PyPI packages"
authors = ["Eli Jun"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
matplotlib-inline = ">=0.1.0,<3.9.0"
pyzmq = "*"
azure-quantum = {extras = ["qiskit"], version = "*"}
qsharp = "*"
amazon-braket-algorithm-library = "*"
amazon-braket-sdk = "*"
qiskit-braket-provider = "*"
qiskit = "*"
openqasm3 = "*"
PennyLane-qiskit = "*"
jupyterlab = "*"
notebook = "*"
mitiq = "*"
qupython = "*"
dynacir = "*"
pyscf = "*"
voila = "*"
PennyLane = "*"
projectq = "*"
pulser-pasqal = "*"
pyEPR-quantum = "*"
pyquil = "*"
strangeworks = "*"
jupyterhub = "*"
dockerspawner = "*"
passlib = "*"
ipython = "*"
pycurl = "*"
tornado = "*"
etcd3 = "*"
sparse = "*"
opt-einsum = "*"
bcrypt = "*"
jupyterhub-idle-culler = "*"
jupyterhub-nativeauthenticator = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
install = "pip install -c https://qisk.it/1-0-constraints qiskit"
