apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: jupyterlab-setup-
  annotations:
    description: "Workflow to set up JupyterLab"
spec:
  entrypoint: jupyterlab-workflow-template
  volumes:
  - name: workdir
    persistentVolumeClaim:
      claimName: jupyterlab-pvc
  workflowTemplateRef:
    name: jupyterlab-workflow-template
