version: '3.8'

services:
  jupyterlab:
    build: .
    image: elijun831/qiskit-on-docker:jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app/notebooks:rw
      - ./data:/home/appuser/data:rw
      - .:/app:rw
      - ./notebooks:/home/appuser/notebooks:rw
      - ./jupyter_lab_config.py:/home/appuser/.jupyter/jupyter_lab_config.py:ro
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - JUPYTER_ENABLE_LAB=yes
      - NB_UID=0
      - NB_GID=0
    command: ["poetry", "run", "jupyter", "lab", "--config=/home/appuser/.jupyter/jupyter_lab_config.py"]
    networks:
      - mynetwork
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    cap_drop:
      - all
    tmpfs:
      - /tmp
    depends_on:
      - etcd

  etcd:
    image: quay.io/coreos/etcd:v3.4.13
    container_name: etcd
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd_data:/etcd-data
    environment:
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    networks:
      - mynetwork

volumes:
  etcd_data:
    driver: local

networks:
  mynetwork:
    driver: bridge
