apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-config
data:
  etcd.conf: |
    # This is a YAML-formatted file.
    # Specify a list of URLs to pass to etcd's --initial-cluster flag.
    initial-cluster: etcd=http://etcd:2380
    # Specify the name for this member.
    name: etcd
    # Listen on all IP addresses.
    listen-client-urls: http://0.0.0.0:2379
    # Advertise client URLs.
    advertise-client-urls: http://etcd:2379
