apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cilium-admin
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: control
    meta.helm.sh/release-namespace: default
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
