apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cilium
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: cilium
  template:
    metadata:
      labels:
        k8s-app: cilium
    spec:
      serviceAccountName: cilium
      containers:
      - name: cilium
        image: "cilium/cilium:stable"
        command:
        - cilium-agent
        args:
        - --kvstore=etcd
        - --kvstore-opt=etcd.config=/var/lib/etcd-config/etcd.config
        - --enable-ipv4={{ .Values.cilium.ipv4.enabled }}
        - --enable-ipv6={{ .Values.cilium.ipv6.enabled }}
        - --enable-remote-node-identity=true
        - --container-runtime=none
        - --tunnel={{ .Values.cilium.tunnel }}
        - --cluster-name={{ .Values.cilium.clusterName }}
        - --identity-allocation-mode={{ .Values.cilium.identityAllocationMode }}
        - --native-routing-cidr={{ .Values.cilium.nativeRoutingCIDR }}
        - --enable-host-reachable-services={{ .Values.cilium.hostReachableServices }}
        - --auto-direct-node-routes={{ .Values.cilium.directNodeRoutes }}
        volumeMounts:
        - mountPath: /var/lib/etcd-config
          name: etcd-config
      volumes:
      - name: etcd-config
        configMap:
          name: {{ .Values.cilium.kvstore.configMap }}
