apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qiskit-monitoring.fullname" . }}-combined-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
  
  cilium.conf: |-
    # Cilium configuration
    debug: "false"
    disable-envoy-version-check: "true"
    enable-ipv6: "false"
    enable-k8s-event-handover: "true"
    enable-l7-proxy: "true"
    enable-node-port: "true"
    enable-remote-node-identity: "true"
    enable-well-known-identities: "true"
    ipam: "cluster-pool"
    kube-proxy-replacement: "strict"
    masquerade: "true"
    monitor-aggregation: "low"
    native-routing-cidr: "10.0.0.0/8"
    preallocate-bpf-maps: "true"
    sidecar-istio-proxy-image: "cilium/istio_proxy"
    tunnel: "vxlan"
  
  # Add other configurations as needed
