apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: control-etcd
  namespace: default
spec:
  serviceName: "etcd"
  replicas: 1
  selector:
    matchLabels:
      app: control-etcd
  template:
    metadata:
      labels:
        app: control-etcd
    spec:
      containers:
      - name: etcd
        image: bitnami/etcd:latest
        ports:
        - containerPort: 2379
          name: client
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: data
          mountPath: /var/lib/etcd
        command:
        - /opt/bitnami/etcd/bin/etcd
        args:
        - --data-dir=/var/lib/etcd
        - --name=$(POD_NAME)
        - --initial-advertise-peer-urls=http://$(POD_NAME).control-etcd.default.svc.cluster.local:2380
        - --listen-peer-urls=http://0.0.0.0:2380
        - --listen-client-urls=http://0.0.0.0:2379
        - --advertise-client-urls=http://$(POD_NAME).control-etcd.default.svc.cluster.local:2379
        - --initial-cluster=$(POD_NAME)=http://$(POD_NAME).control-etcd.default.svc.cluster.local:2380
        - --initial-cluster-state=new
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
