apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-etcd
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 2379
    name: client
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-etcd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-etcd
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: "{{ .Release.Name }}-etcd"
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-etcd
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.4.13
        ports:
        - containerPort: 2379
          name: client
        volumeMounts:
        - name: data
          mountPath: /var/lib/etcd
        command:
        - /usr/local/bin/etcd
        args:
        - --data-dir=/var/lib/etcd
        - --name=$(POD_NAME)
        - --initial-advertise-peer-urls=http://$(POD_NAME).{{ .Release.Name }}-etcd.{{ .Release.Namespace }}.svc.cluster.local:2380
        - --listen-peer-urls=http://0.0.0.0:2380
        - --listen-client-urls=http://0.0.0.0:2379
        - --advertise-client-urls=http://$(POD_NAME).{{ .Release.Name }}-etcd.{{ .Release.Namespace }}.svc.cluster.local:2379
        - --initial-cluster=$(POD_NAME)=http://$(POD_NAME).{{ .Release.Name }}-etcd.{{ .Release.Namespace }}.svc.cluster.local:2380
        - --initial-cluster-state=new
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
