apiVersion: v1
kind: Secret
metadata:
  name: kiali
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: control
    meta.helm.sh/release-namespace: default
type: Opaque
data:
  username: a2lhbGk=  # base64 encoding of "kiali"
  passphrase: cGFzc3dvcmQ=  # base64 encoding of "password"
