apiVersion: v1
kind: Secret
metadata:
  name: kiali
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.kiali.secret.username | b64enc | quote }}
  passphrase: {{ .Values.kiali.secret.passphrase | b64enc | quote }}
  signingKey: {{ .Values.kiali.secret.signingKey | b64enc | quote }}
