apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: default
type: Opaque
data:
  # base64 encoded values for username and passphrase
  username: a2lhbGk=  # base64 encoding of "kiali"
  passphrase: cGFzc3dvcmQ=  # base64 encoding of "password"
